version: "3"

services:

  data:
    build:
      context: "."
    domainname: reddit
    image: reddit.azurecr.io/data
    container_name: data
    command: python data.py --publish 7200
    env_file:
      - .env
    deploy:
      resources:
        reservations:
          cpus: "1"
          memory: "4G"
    restart: always

  visualize:
    build:
      context: "."
    image: reddit.azurecr.io/visualize
    container_name: visualize
    command: streamlit run visualize.py --server.port 80
    ports:
      - "80:80"
    env_file:
      - .env
    deploy:
      resources:
        reservations:
          cpus: "1"
          memory: "4G"
    restart: always
