name: wsbyolo
channels:
  - defaults
  - conda-forge
dependencies:
  - altair=4.1.0
  - autopep8=1.5.4
  - pandas=1.2.1
  - pip=20.3.3
  - praw=7.0.0
  - python=3.8.5
  - tqdm=4.56.0
  - pip:
    - simple-crypt==4.1.7