name: wsbyolo
channels:
  - defaults
  - conda-forge
dependencies:
  - altair=4.1.0
  - autopep8=1.5.4
  - lxml=4.6.2
  - pandas=1.2.1
  - pip=20.3.3
  - praw=7.0.0
  - pytables=3.6.1
  - python=3.8.5
  - tqdm=4.56.0
  - pip:
    - pycryptodome==3.9.9
    - simple-crypt==4.1.7